### ISSUE TITLE
Identifiants des matrixset WMTS

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewer#32]
En essayant de faire fonctionner mviewer avec le service WMTS de osm.geopicardie.fr, je me suis rendu compte que mviewer s'attend à trouver des identifiants de matrixset particuliers :
'EPSG:3857', 'EPSG:4326','EPSG:2154' et 'PM'
(cf. https://github.com/geobretagne/mviewer/blob/master/lib/mviewer.js#L1846-L1855)

Est-ce qu'il s'agit d'une spécificité de GéoBretagne ? Est-ce l'usage de ces identifiants fait l'objet d'une standardisation, de bonnes pratiques ?

**Comment by spelhate** [comment]
Il s'agit d'une spécificité geowebcache exemple ici : (https://osm.geobretagne.fr/gwc01/service/wmts?REQUEST=getcapabilities) à laquelle j'ai adapté le mviewer ne disposant pas à cette époque d'un parser de capacités WMTS. Julien S a réalisé une pull request (https://github.com/geobretagne/mviewer/pull/28)
permettant de parser les capacités WMTS. Pour exploiter cete fonctionnalité, il faut ajouter le paramètre fromcapacity="true" (baselayer) dans le fichier config.xml

**Comment by bchartier** [comment]
> Il s'agit d'une spécificité geowebcache exemple ici

En fait, dans GeoWebCache on peut les nommer comme on veut mais par défaut GWC vient avec des grilles déjà paramétrées et nommées de la sorte.
Je vais voir pour qu'on renomme les tilematrixset de osm.geopicardie.fr pour que ce soit cohérent avec ces grilles.

> Pour exploiter cete fonctionnalité, il faut ajouter le paramètre fromcapacity="true"

Bah, j'ai testé avec cette option également mais je n'ai pas réussi à le faire fonctionner. Je vais étudier cela plus en détail.

Merci encore pour tes réponses rapides et précises.

**Comment by bchartier** [comment]
Je reviens sur le nommage des tilematrixset car je me rends compte de 2 choses :

a. dans Mapproxy, la définition des tilematrixset se fait dans un fichier yaml :
Exemple :
```
    cnigl93:
        srs: 'EPSG:2154'
        tile_size: [256,256]
        res: [104579.224549894,52277.5323537906,26135.4870785954,13066.8913818,6533.22860411345,3266.55952446267,1633.26600459742,816.629554986023,408.313914676837,204.156741510902,102.078316783241,51.0391448966111,25.5195690742694,12.7597836936475,6.37989163596649,3.18994576530531,1.59497286949772,0.797486431547441,0.398743214900605,0.19937160727568,0.0996858036960475,0.0498429018189199]
```
Mettre un ":" dans le nom du tilematrixset risque de ne pas être pratique dans un fichier yaml.

b. Le guide du CNIG et la spec WMTS utilise des identifiants. Je pense que ce serait plus simple pour tout le monde si on reprenait les identifiants proposés dans le guide du CNIG.

Qu'en pensez-vous ? C'est sûr que cela implique de changer les paramétrages de nos services WMTS et du mviewer.
